version: "2"
services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    container_name: "efishery-backend-auth"
    command: npm start